In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
df = pd.read_csv('Spam_Data.csv')

In [15]:
df

Spam                                               Text
0        0  Go until jurong point, crazy.. Available only ...
1        0                      Ok lar... Joking wif u oni...
2        1  Free entry in 2 a wkly comp to win FA Cup fina...
3        0  U dun say so early hor... U c already then say...
4        0  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567     1  This is the 2nd time we have tried 2 contact u...
5568     0              Will Ì_ b going to esplanade fr home?
5569     0  Pity, * was in mood for that. So...any other s...
5570     0  The guy did some bitching but I acted like i'd...
5571     0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [16]:
df['Spam'].value_counts()

0    4825
1     747
Name: Spam, dtype: int64

In [17]:
df.isnull().sum()

Spam    0
Text    0
dtype: int64

# Separate X and Y

In [32]:
x = df.Text.values

In [33]:
y = df.Spam.values

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

# Data Preprocessing

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
cv = CountVectorizer()

In [38]:
x_train=cv.fit_transform(xtrain)

In [39]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML Algorith

In [41]:
from sklearn.naive_bayes import MultinomialNB

In [42]:
model=MultinomialNB()

In [43]:
model.fit(x_train,ytrain)

MultinomialNB()

In [44]:
x_test=cv.transform(xtest)

In [46]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
model.score(x_test,ytest)

0.9865470852017937

# Performance

In [48]:
pred = model.predict(x_test)

In [49]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(ytest,pred)

0.9865470852017937

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
confusion_matrix(ytest,pred)

array([[952,   2],
       [ 13, 148]], dtype=int64)

In [56]:
from sklearn.metrics import classification_report

In [57]:
classification_report(ytest,pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       954\n           1       0.99      0.92      0.95       161\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.96      0.97      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [58]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       954
           1       0.99      0.92      0.95       161

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

